version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=1
      - SECRET_KEY=supersecret
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_NAME=eventdb
      - DB_USER=eventuser
      - DB_PASSWORD=eventpass
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  postgres_data:
  static_volume:

networks:
  appnet:
