# Generated by Django 4.2.21 on 2025-05-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_rule",
                    models.TextField(
                        blank=True, help_text="e.g. 'FREQ=WEEKLY;BYDAY=MO,WE,FR'"
                    ),
                ),
            ],
        ),
    ]
